CREATE TABLE "public"."fund" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "code" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "management" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "custodian" varchar(255) COLLATE "pg_catalog"."default",
  "fund_type" varchar(255) COLLATE "pg_catalog"."default",
  "found_date" timestamptz(6) NOT NULL,
  "due_date" timestamptz(6),
  "list_date" timestamptz(6),
  "issue_date" timestamptz(6),
  "delist_date" timestamptz(6),
  "issue_amount" numeric(12,2),
  "m_fee" numeric(12,2),
  "c_fee" numeric(12,2),
  "duration_year" float4,
  "p_value" numeric(12,2) NOT NULL DEFAULT 0,
  "min_amount" numeric NOT NULL DEFAULT 0,
  "exp_return" float4,
  "benchmark" varchar(255) COLLATE "pg_catalog"."default",
  "status" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "invest_type" varchar(255) COLLATE "pg_catalog"."default",
  "type" varchar(255) COLLATE "pg_catalog"."default",
  "trustee" varchar(255) COLLATE "pg_catalog"."default",
  "purc_startdate" timestamptz(6),
  "redm_startdate" timestamptz(6),
  "market" varchar(255) COLLATE "pg_catalog"."default",
  CONSTRAINT "fund_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."fund" 
  OWNER TO "root";

CREATE UNIQUE INDEX "uni_code" ON "public"."fund" USING btree (
  "code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

COMMENT ON COLUMN "public"."fund"."name" IS '简称';

COMMENT ON COLUMN "public"."fund"."management" IS '管理人';

COMMENT ON COLUMN "public"."fund"."custodian" IS '托管人';

COMMENT ON COLUMN "public"."fund"."fund_type" IS '投资类型';

COMMENT ON COLUMN "public"."fund"."found_date" IS '成立日期';

COMMENT ON COLUMN "public"."fund"."due_date" IS '到期日期';

COMMENT ON COLUMN "public"."fund"."list_date" IS '上市日期';

COMMENT ON COLUMN "public"."fund"."issue_date" IS '发行日期';

COMMENT ON COLUMN "public"."fund"."delist_date" IS '退市日期';

COMMENT ON COLUMN "public"."fund"."issue_amount" IS '发行份额';

COMMENT ON COLUMN "public"."fund"."m_fee" IS '管理费';

COMMENT ON COLUMN "public"."fund"."c_fee" IS '托管费';

COMMENT ON COLUMN "public"."fund"."duration_year" IS '存续期';

COMMENT ON COLUMN "public"."fund"."p_value" IS '面值';

COMMENT ON COLUMN "public"."fund"."min_amount" IS '起点金额（万元）';

COMMENT ON COLUMN "public"."fund"."exp_return" IS '预期收益';

COMMENT ON COLUMN "public"."fund"."benchmark" IS '业绩比较基准';

COMMENT ON COLUMN "public"."fund"."status" IS '存续状态D摘牌 I发行 L已上市';

COMMENT ON COLUMN "public"."fund"."invest_type" IS '投资风格';

COMMENT ON COLUMN "public"."fund"."type" IS '基金类型';

COMMENT ON COLUMN "public"."fund"."trustee" IS '受托人';

COMMENT ON COLUMN "public"."fund"."purc_startdate" IS '日常申购起始日';

COMMENT ON COLUMN "public"."fund"."redm_startdate" IS '日常赎回起始日';

COMMENT ON COLUMN "public"."fund"."market" IS 'E场内O场外';

CREATE TABLE "public"."fund_market" (
  "time" timestamptz(6) NOT NULL,
  "symbol" text COLLATE "pg_catalog"."default" NOT NULL,
  "open" numeric(12,4) NOT NULL,
  "high" numeric(12,4) NOT NULL,
  "low" numeric(12,4) NOT NULL,
  "close" numeric(12,4) NOT NULL,
  "pre_close" numeric(12,4) NOT NULL,
  "change" numeric(12,4) NOT NULL,
  "pct_chg" numeric(12,4) NOT NULL,
  "vol" numeric(14,4) NOT NULL,
  "amount" numeric(14,4) NOT NULL,
  "created_at" timestamptz(6) NOT NULL,
  "updated_at" timestamptz(6) NOT NULL
)
;

ALTER TABLE "public"."fund_market" 
  OWNER TO "root";

CREATE INDEX "fund_market_time_idx" ON "public"."fund_market" USING btree (
  "time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);

CREATE UNIQUE INDEX "uni_symbol_time" ON "public"."fund_market" USING btree (
  "time" "pg_catalog"."timestamptz_ops" ASC NULLS LAST,
  "symbol" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE TRIGGER "ts_insert_blocker" BEFORE INSERT ON "public"."fund_market"
FOR EACH ROW
EXECUTE PROCEDURE "_timescaledb_functions"."insert_blocker"();